### ISSUE TITLE
Packet Overflows

### ISSUE THREAD

**Issue by Flecked42** [j0zzz/JoeQuake#105]
Info is on QS https://github.com/sezero/quakespasm/issues/59

**Comment by Flecked42** [comment]
https://github.com/j0zzz/JoeQuake/blob/8f7407bd01d3b0550107074073676f888a8e0d43/trunk/quakedef.h#L73
i increased that to 64000 and it does seem to to the issue

**Comment by j0zzz** [comment]
Fixed in commit 4fcec00
