### ISSUE TITLE
Issue with loading some maps from Paril3.0

### ISSUE THREAD

**Issue by Flecked42** [j0zzz/JoeQuake#107]
JoeQuake will close with no error when loading these maps from Paril3.0 https://www.slipseer.com/index.php?resources/peril3-0.253/

cravasse
north
start
prison
village

Tested maps in QS and they load fine.

**Comment by Flecked42** [comment]
Changing these values to FLT_MAX seems to fix the issue

https://github.com/j0zzz/JoeQuake/blob/8f7407bd01d3b0550107074073676f888a8e0d43/trunk/gl_model.c#L1053
https://github.com/j0zzz/JoeQuake/blob/8f7407bd01d3b0550107074073676f888a8e0d43/trunk/gl_model.c#L1054

**Comment by Flecked42** [comment]
QS commit with more info https://github.com/sezero/quakespasm/commit/ad3aadb3735971357a0e3e627cd56f47e0bb2792

**Comment by j0zzz** [comment]
Fixed in commit 344ffcb
