### ISSUE TITLE
Strange model skin issue

### ISSUE THREAD

**Issue by Flecked42** [j0zzz/JoeQuake#111]
Map is rm_carcosa from Re:Mobilize

![joequake001](https://github.com/j0zzz/JoeQuake/assets/90434262/c49965ef-1c2f-4803-a5c2-c460bea6e905)

Tested in QS and they look good.

**Comment by Flecked42** [comment]
![Screenshot (57)](https://github.com/j0zzz/JoeQuake/assets/90434262/518e338d-554f-4395-ba05-32b2b4950df3)

There's another model named knight in the pak0 and JoeQuake is using that models skin on the regular knight.

**Comment by j0zzz** [comment]
Fixed in commit d67dbaa
