### ISSUE TITLE
Ghost splits: Rewinding a demo during intermission shows multiple splits per level

### ISSUE THREAD

**Issue by matthewearl** [j0zzz/JoeQuake#115]
![joequake016](https://github.com/j0zzz/JoeQuake/assets/1709642/cd36da20-d334-4e4a-afaf-a41f5131ccd0)
Repro steps:

1. Play a demo with a ghost enabled.
2. When the demo reaches the intermission hit rewind.
3. When the demo is no longer in the intermission hit forward.

When the demo hits the intermission again two times for the same level will be displayed on the intermission.  Repeat to show even more times.

**Comment by j0zzz** [comment]
Fixed in commit cea3810
