### ISSUE TITLE
Add GL_DEPTH_CLAMP_NV

### ISSUE THREAD

**Issue by Flecked42** [j0zzz/JoeQuake#129]
Fixes issues with the water surface when going in and out of water.

QS commits for it

https://github.com/sezero/quakespasm/commit/74c47869742cce169b8569a33cd292d36d43917a
https://github.com/sezero/quakespasm/commit/14164418d8403eff31dbefb469259b2b6020f740

More info here https://github.com/sezero/quakespasm/issues/62

Added `glEnable(GL_DEPTH_CLAMP_NV);` here and its seems to work good

![Screenshot (64)](https://github.com/j0zzz/JoeQuake/assets/90434262/a77c3747-a27f-41b8-95ca-320f2a9411ed)

**Comment by Flecked42** [comment]
Before

![joequake001](https://github.com/j0zzz/JoeQuake/assets/90434262/195b4ef4-7f2b-4b5c-8eb6-041abcf590fb)


After

![joequake000](https://github.com/j0zzz/JoeQuake/assets/90434262/660814e8-e1f4-4a82-9740-1063b6199793)

**Comment by j0zzz** [comment]
Fixed in commit 9790f40
