### ISSUE TITLE
glDrawElements fails with GL_INVALID_OPERATION on Intel Corporation Iris Plus Graphics G7 (laptop GPU)

### ISSUE THREAD

**Issue by j0zzz** [j0zzz/JoeQuake#132]
Issue occurs when the alias model drawing shaders are executed. The shader compiler does not show any errors.

JoeQuake uses a texture buffer object (TBO) to upload a 64K byte array to GLSL. This array contains precomputed lighting information, which is sufficient for vertex lighting. In the vertex shader, an item from this array is obtained with the texelFetch() method call. If I remove this call, the GL_INVALID_OPERATION error is not returned any more and the alias models are drawn - obviously with incorrect lighting.

Is there any way to query if the GPU is capable to serve the texelFetch() call? Or what else can I try?
The only additional OpenGL method required for TBOs is glTexBuffer, but its availability is checked at startup and is usually found in the opengl32.dll, so that doesn't help.

I had this issue for more than 2 years when I was trying to fix this for many weeks until I ended up using shader storage buffer object (SSBO) instead, but the problem with that solution is that it required GLSL version 4.3 which turned out to be a major performance death sentence if you combine with regular OpenGL calls to due querying and feeding the ModelView and Projection matrices before every shader execution.

@sezero, @ericw, @andrei-drexler you guys have any tips, ideas?

**Comment by Flecked42** [comment]
I put in that change and GLSL is enabled for me. Maybe that GPU doesn't support GLSL?
