### ISSUE TITLE
Weapon draw still changes with FOV when cl_gun_fovscale is set to 1

### ISSUE THREAD

**Issue by Konkonfaux** [j0zzz/JoeQuake#146]
Not sure whether this is how it's supposed to work, but on Quakespasm and forks, it fixes that.

FOV 90
![joequake014](https://github.com/j0zzz/JoeQuake/assets/67092414/77e22835-5506-4224-b8a6-3bb358aeeaa0)

FOV 100
![joequake015](https://github.com/j0zzz/JoeQuake/assets/67092414/119ff17a-4c2e-41e7-8614-6e4eacfe1f7c)

**Comment by j0zzz** [comment]
Fixed in commit b006708
