### ISSUE TITLE
GL_Upload8 error

### ISSUE THREAD

**Issue by Flecked42** [j0zzz/JoeQuake#153]
happens when loading s3m1_fw from https://www.slipseer.com/index.php?resources/snack-pack-3-trick-or-treat.280/

![Screenshot (82)](https://github.com/j0zzz/JoeQuake/assets/90434262/e1c2ab21-9d72-46cc-9902-8c1c2be13fd3)

**Comment by j0zzz** [comment]
Fixed in commit 49ee1f0
