### ISSUE TITLE
More codecs than just xvid and divx?

### ISSUE THREAD

**Issue by root-reindeer-flotilla** [j0zzz/JoeQuake#154]
Hey, I'm trying to use the capture function and I've only found three codecs that work with JoeQuake even though the manual says "etc".

"0"/uncompressed is way too big, like 2 seconds of footage per 2gb file.
"xvid"/"divx" are really old codecs that don't look very good.

Is there a way to use different codecs? Ive tried using the fourcc code for multiple different codecs such as "x264" "h264" "vp01" "ffv1".

**Comment by j0zzz** [comment]
Hi there,
It is the installed codec's fourCC code that is required to be defined as the value of the capture_codec variable. There are tools you can use to find out what codecs are installed on your PC and what are the fourCC codes of these codecs. I use the free tool called VirtualDub: https://virtualdub.sourceforge.net/
After starting it, open the menu Video -> Compression... On the displayed dialog you can see all your video codecs installed. Select any of them to have the fourCC code displayed. That's the one you may use in JoeQuake.
![image](https://github.com/j0zzz/JoeQuake/assets/57400093/3a98522c-59fd-4e58-aed9-8b05e2efea09)

But honestly, in today's world I wouldn't bother with JoeQuake's built-in capturing method, especially if you want to record long videos. Modern videocards have real-time capturing capability, I'd suggest using a tool like OBS or ShadowPlay instead.
