### ISSUE TITLE
Crash on map lim_daviddg

### ISSUE THREAD

**Issue by Flecked42** [j0zzz/JoeQuake#155]
Download mod here https://www.slipseer.com/index.php?resources/liminal-spaces-jam.359/

QS commits for it https://github.com/sezero/quakespasm/commit/e35ecad1847de7b2d3382ce180c145015cc1e379
https://github.com/sezero/quakespasm/commit/c1bbf7d024b4b2b3ce2f14925de9a9a2b096b9a1

**Comment by j0zzz** [comment]
Fixed in commits:
58b6e2c
42b65ee
