### ISSUE TITLE
Issue with map 180

### ISSUE THREAD

**Issue by Flecked42** [j0zzz/JoeQuake#156]
![joequake000](https://github.com/user-attachments/assets/f540fc44-4469-49c4-8fe1-424a0556e497)

Couldn't find a commit on QS but here's one from IW https://github.com/andrei-drexler/ironwail/commit/403c458e3b6cbf0c4df6d7568e7f36515ff345e0

**Comment by Flecked42** [comment]
Forgot to mention. `r_fullbright 1` fixes it

**Comment by j0zzz** [comment]
Fixed in commit 9c8c937
