### ISSUE TITLE
Implement r_ambient (for gl)

### ISSUE THREAD

**Issue by matthewearl** [j0zzz/JoeQuake#171]
This is already a thing in the software renderer.  It adds an ambient light level to the lightmap and to alias models. It would be useful to eliminate fully dark areas in levels like e4m4, without having to fully destroy your retinas with r_fullbright.  Ideally it would work without restarting the map (unlike the software implementation) but that may be trickier.

**Comment by j0zzz** [comment]
Something like this? @matthewearl
![joequake119](https://github.com/user-attachments/assets/737f15e6-80ef-4b64-928f-1e784d6654c8)

**Comment by matthewearl** [comment]
Yes, that looks right.  We'd want to be sure alias models in the shadow aren't fully dark either

**Comment by j0zzz** [comment]
Done in the following commits:
f315b9f
4f75218
9b2d604

**Comment by matthewearl** [comment]
Awesome, I'll take a look when I get a moment.

**Comment by matthewearl** [comment]
Code looks great, and it works well too :+1:
