### ISSUE TITLE
Movements always interpolated for non-LERP_MOVESTEP

### ISSUE THREAD

**Issue by matthewearl** [j0zzz/JoeQuake#179]
Reproduction steps:

1.  Record a demo where the player moves.
2. Watch it back in freefly, with `gl_interpolate_moves 0`.
3. Observe that the player moves smoothly.

I'm pretty sure it can be fixed like so:

```diff
diff --git a/trunk/cl_main.c b/trunk/cl_main.c
index 892e424..8f9c36e 100644
--- a/trunk/cl_main.c
+++ b/trunk/cl_main.c
@@ -837,7 +837,7 @@ void CL_RelinkEntities (void)

 #ifdef GLQUAKE
                        //johnfitz -- don't cl_lerp entities that will be r_lerped
-                       if (gl_interpolate_moves.value && (ent->lerpflags & LERP_MOVESTEP))
+                       if (!gl_interpolate_moves.value || (ent->lerpflags & LERP_MOVESTEP))
                                f = 1;
                        //johnfitz
 #endif
```

This is handy for visualizing FPS tricks: without it the player just moves smoothly from point to point, and you get no notion of the distance skipped between frames.  It's probably useful for other things too, and moreover I'd say this is the expected behavior when you turn movement interpolation off.

Having said that it has the unfortunate side effect of making camera movement stuttery (limited to the server frame rate) the first person too.  Perhaps this is fine? Maybe we can add an exception for the view entity when in first person?  Anyway, not raising a PR for this yet since I'm not sure what the desired behavior is.

**Comment by matthewearl** [comment]
I've got a PR here that disables interpolation for cl_bbox, which I think we probably want anyway, and might be a good compromise regarding the above.  https://github.com/j0zzz/JoeQuake/pull/180

**Comment by j0zzz** [comment]
> I've got a PR here that disables interpolation for cl_bbox, which I think we probably want anyway, and might be a good compromise regarding the above

I Agree. Wouldn't like to make the player position lerping switchable, especially not binding to an existing cvar which plays a slightly different role (gl_interpolate_movement). I think it's a great compromise - as you said - to only disable the lerping only for the bboxes. When they are switched on, it highlights the movements in a great way now.

**Comment by matthewearl** [comment]
Cool, closing since we're sticking with the existing behavior
