### ISSUE TITLE
"AllocBlock: full" error

### ISSUE THREAD

**Issue by Flecked42** [j0zzz/JoeQuake#31]
![Capture](https://user-images.githubusercontent.com/90434262/140657408-5c2d31a7-0632-48c4-95f7-c6c8952830e3.jpg)

Error happens on map ravenkeep from https://www.quaddicted.com/reviews/ravenkeep.html

Also happens on map sinister625_palmlix from https://www.quaddicted.com/reviews/sinister625.html

**Comment by Flecked42** [comment]
Noticed your commit https://github.com/j0zzz/JoeQuake/commit/3b7e44855ee907a66c47c6651d3b59bb5c92da2f issues with dynamic lightmap allocation

Not sure if you've seen this commit, but maybe it would help https://github.com/sezero/quakespasm/commit/e041b958c778e823806a22c19cad37e8f9d22210

**Comment by j0zzz** [comment]
Fixed in commit 8f7407b
