### ISSUE TITLE
Monsters are not lit properly in fog

### ISSUE THREAD

**Issue by Flecked42** [j0zzz/JoeQuake#34]
![140658347-3383ada0-b451-4544-acfb-30d2bc226d39](https://user-images.githubusercontent.com/90434262/140658710-32e8da81-d9ec-43d3-b5b8-270c62c2da11.jpg)

Map in image is bm_chrisholden from https://www.quaddicted.com/reviews/bluemonday_v2.html

This happens in the version you sent me with the fixed vertex lights. It doesn't happen in the public 17.2 release.

**Comment by j0zzz** [comment]
This occurred only in an unreleased build tested by @Flecked42
I've already corrected this issue, but on this specific map the fog is way too intensive now. Other maps doesn't have this problem. I will investigate it further in the near future.

**Comment by j0zzz** [comment]
Fixed in commit 95e14008
