### ISSUE TITLE
Trigger forces game to lock up

### ISSUE THREAD

**Issue by Flecked42** [j0zzz/JoeQuake#36]
![Capture](https://user-images.githubusercontent.com/90434262/140659745-e6dca92d-671c-45e5-8f99-27dde7f23057.jpg)

Game locks up when hitting this trigger in map dm4jam_ww from https://www.quaddicted.com/reviews/dm4jam.html

The trigger is right in front of the starting spawn.

**Comment by j0zzz** [comment]
Fixed in commit 5d93302
