### ISSUE TITLE
Headless video rendering

### ISSUE THREAD

**Issue by msikma** [j0zzz/JoeQuake#38]
Hi there, I'm a longtime user and fan of Joequake. I was wondering if it's possible to do headless video capturing, i.e. rendering video to a file without starting the graphical interface itself, and just using command line. I thought it might be nice to be able to automate this for bulk capture and processing of demo files. Headless mode would just make it a bit easier on my computer and potentially less of a nuisance while doing other things.

As far as I can tell it's not possible, but maybe there are potentially other solutions to this?

**Comment by j0zzz** [comment]
JoeQuake uses the windows built-in VFW (video for windows) interface. This works as a blackbox, basically the actual video buffer (as bytes) is captured frame-by-frame and passed to the VFW interface along with the sound buffer, and it constructs the target AVI file. So yeah, until we stick with the VFW interface, what you ask will not work. And switching to another video capturing library would be a ton of work which is not planned at all at the moment, sorry.

**Comment by msikma** [comment]
Interesting, thanks for the comment! I'm really not a Windows guy so I don't know much about any of this (I'm running JQ in a VM mostly). Does the VFW interface require a window to be present or is that just a result of how the game itself operates? Like if it has a buffer that's being passed along to something maybe it's feasible to pass that on to something like ffmpeg? Either way I understand it's not a simple change.
