### ISSUE TITLE
Last frame of a demo is messed up

### ISSUE THREAD

**Issue by Flecked42** [j0zzz/JoeQuake#42]
![joequake000](https://user-images.githubusercontent.com/90434262/158260744-52caf4a3-c804-469f-a2b1-dbd658f2808f.jpg)

Thanks to https://github.com/andrei-drexler for all the info.

I spent a bit of time debugging this, and the short version is that after the demo ends, the 3d scene is no longer rendered, but the intermission screen still is, effectively on top of garbage memory. The sequence of events that causes this is:
- svc_disconnect is parsed, calling Host_EndGame, which in turn calls CL_Disconnect, which sets cls.signon to 0
https://github.com/j0zzz/JoeQuake/blob/69b8359ecb760681d4b62f97e04b26e51540ac3c/trunk/cl_parse.c#L1264-L1265
https://github.com/j0zzz/JoeQuake/blob/943c135b3a7f0c99bfeaeff4fc64a3a03a00e84e/trunk/host.c#L127-L128
https://github.com/j0zzz/JoeQuake/blob/48915dd45486ae8d09f9f272bbff9db6d4ace39b/trunk/cl_main.c#L212
- when the next frame is rendered, SCR_UpdateScreen calls SCR_SetUpToDrawConsole, which sets con_forcedup to 1
https://github.com/j0zzz/JoeQuake/blob/dfe905fef4eb8a2066eb626041165669dc98608a/trunk/gl_screen.c#L1086
https://github.com/j0zzz/JoeQuake/blob/dfe905fef4eb8a2066eb626041165669dc98608a/trunk/gl_screen.c#L584
- SCR_UpdateScreen then calls V_RenderView, which checks con_forcedup and returns (without clearing the screen or rendering anything)
https://github.com/j0zzz/JoeQuake/blob/53032d6385e0bd481a11b4f8a0f183dc7cce9c9c/trunk/view.c#L1482-L1485
- SCR_UpdateScreen continues, reaching a block of code that checks if cl.intermission is 1 and if key_dest is key_game, and then proceeds to render the intermission screen
https://github.com/j0zzz/JoeQuake/blob/dfe905fef4eb8a2066eb626041165669dc98608a/trunk/gl_screen.c#L1115-L1122

An easy fix would be to reset cl.intermission to 0 in CL_Disconnect, which is what QS and vkQuake do:
https://github.com/sezero/quakespasm/blob/065c1582548dd8e25f5102882d5293d5a6cb7add/Quake/cl_main.c#L135
https://github.com/Novum/vkQuake/blob/5279c8aafb50487fa24480decafbc0dc10ae22dc/Quake/cl_main.c#L171

**Comment by j0zzz** [comment]
Fixed in commit 760d5cc.
