### ISSUE TITLE
Issue with static .mdl entities

### ISSUE THREAD

**Issue by Flecked42** [j0zzz/JoeQuake#43]
https://user-images.githubusercontent.com/90434262/158268191-92a80f59-f6fe-40e4-b7ce-f2c785905a34.mp4

https://user-images.githubusercontent.com/90434262/158268200-c1cc8e40-4a48-43dd-b209-e4c009a3de3c.mp4

The map s2m6_alexunder from https://www.quaddicted.com/reviews/snack2.html is a reliable map to test this on as there are two dead ranger mdls at the start.

**Comment by j0zzz** [comment]
Most likely fixed in commit 5183590. Issue will be closed if beta testing ends.

**Comment by j0zzz** [comment]
Confirmed: fixed in commit 5183590
