### ISSUE TITLE
Display monster counts > 3 digits on end screen

### ISSUE THREAD

**Issue by Flecked42** [j0zzz/JoeQuake#47]
Rumor has it Mazu's map in the upcoming Dwell - Episode 2 will have 1155 monsters

Commit for it on Ironwail. https://github.com/andrei-drexler/ironwail/commit/85d042a2ccca4277d190cfa19c9a0699f8ecae0c

Map 1kknights from https://www.quaddicted.com/reviews/dknights.html has 1111 monsters if you're looking for a quick map to test it.

**Comment by j0zzz** [comment]
Fixed in commit 35e4283c
