### ISSUE TITLE
Lightmapped liquid surfaces

### ISSUE THREAD

**Issue by Flecked42** [j0zzz/JoeQuake#48]
The upcoming Dwell - Episode 2 is gonna be one of the first major Quake SP releases to use lightmapped liquids (-splitturb on qbsp in ericw tools).

It's backwards compatible, so maps compiled with -splitturb work fine if the engine doesn't support it.

Commit for it on Ironwail. https://github.com/andrei-drexler/ironwail/commit/3217fad2d6ac515f8f467e57e8e59b0fb14bd2a4

Test map that the Ironwail dev used https://github.com/andrei-drexler/quakespasm/files/7815945/litwater.zip

**Comment by Flecked42** [comment]
Also a commit for it on QuakeSpasm https://github.com/sezero/quakespasm/commit/87835bc3e3749618ef8a414e69b69c8d79780ac6

**Comment by j0zzz** [comment]
Fixed in commit 223ba8fb
