### ISSUE TITLE
issue with loading/unloading HUD/MENU gfx

### ISSUE THREAD

**Issue by Flecked42** [j0zzz/JoeQuake#51]
HUD/MENU gfx don't load/unload properly when switching mods in the menu

https://speeddemosarchive.com/quake/maps/alk1.1.zip is a good mod for testing it.

**Comment by Flecked42** [comment]
Maybe this QS commit can help https://github.com/sezero/quakespasm/commit/ae876c943b2527e0d621bdb4518a88bdb7333382

**Comment by Flecked42** [comment]
I've discovered that after changing mods in the menu, switching "gl_externaltextures_gfx" on and off again with load the HUD/MENU gfx properly.

**Comment by j0zzz** [comment]
Fixed in commit 2ca879d
