### ISSUE TITLE
Some shadows are drawn far away from model when using r_fullbrightskins

### ISSUE THREAD

**Issue by j0zzz** [j0zzz/JoeQuake#53]
![joequake021](https://user-images.githubusercontent.com/57400093/190630809-c4e17e33-8580-4d69-ae30-0e960aab8973.jpg)

**Comment by revelator** [comment]
looks like the trick where you face the shadow polygons downward no longer works correctly, newer been to stable to begin with as it cannot handle slopes but at the time it was the best we could do. Maybe time to consider shadow maps i reckon.

**Comment by matthewearl** [comment]
A similar thing happens with `r_fullbright 1` 
![joequake014](https://github.com/j0zzz/JoeQuake/assets/1709642/396c3622-d655-4873-bc16-84260a01923c)

**Comment by j0zzz** [comment]
Fixed in commit b57b54d
