### ISSUE TITLE
skin taller than 480 error

### ISSUE THREAD

**Issue by Flecked42** [j0zzz/JoeQuake#54]
Not a major issue as I've only seen it once, but i assume its some vanilla limitation.
![skin_error](https://user-images.githubusercontent.com/90434262/190705770-7e2d40df-ffb8-4560-b5e7-e778e81cd7e3.png)

**Comment by Flecked42** [comment]
QS commit https://github.com/sezero/quakespasm/commit/8a72565fd06b36b28de568ae39c0826a17dcc4cf
vkQuake issue with more info https://github.com/Novum/vkQuake/issues/347

**Comment by j0zzz** [comment]
Fixed in commit fb341f6
