### ISSUE TITLE
issue with swinging blades in AD

### ISSUE THREAD

**Issue by Flecked42** [j0zzz/JoeQuake#56]
Swinging blades are black in ad_magna and ad_necrokeep

Tested in QuakeSpasm and they look good.

![joequake000](https://user-images.githubusercontent.com/90434262/191108022-ea927e80-3db2-4a4d-be62-dcc44d60f531.jpg)
![joequake001](https://user-images.githubusercontent.com/90434262/191108025-d02a9c89-f0fe-4604-a8f4-0ec400ac5ab5.jpg)

There's also swinging blades in ad_lavatomb, but those look good.

**Comment by Flecked42** [comment]
Commit for fixed same issue in Ironwail https://github.com/andrei-drexler/ironwail/commit/ed0e44fbed3b0f25c602666a4d312150bb1105bd

**Comment by Flecked42** [comment]
Commit for fixing the same issue on QS https://github.com/sezero/quakespasm/commit/7e4c88aed953ae559410fd30163a033812828f20

**Comment by j0zzz** [comment]
Fixed in commit fdd634b
