### ISSUE TITLE
issue with buttons that move towards the player

### ISSUE THREAD

**Issue by Flecked42** [j0zzz/JoeQuake#57]
Buttons that move towards the player can cause the player to get stuck and unable to move.

Example of it happening is in one of the Travail maps https://www.quaddicted.com/filebase/travail.zip

save at the spot [s0.zip](https://github.com/j0zzz/JoeQuake/files/9649880/s0.zip)

Commit for it on QS https://github.com/sezero/quakespasm/commit/a89063a5ff9bead0a140f315bfd10ac601a62e37
Another commit for it on QS https://github.com/sezero/quakespasm/commit/1ccd0b998a2192caeaa1099207c50048bde220ba

**Comment by j0zzz** [comment]
Fixed in commit 7986864
