### ISSUE TITLE
"find" command from QS

### ISSUE THREAD

**Issue by Flecked42** [j0zzz/JoeQuake#58]
Extremely useful for searching for console cvars and commands. Also referred to as "apropos" command.

Commit for it on QS https://github.com/sezero/quakespasm/commit/43b509ba4fcf484186ccaf811ac4e5147f355156
Another commit for it on QS: https://github.com/sezero/quakespasm/commit/e24916cfc02b60329664e8b3165cc300652e0722

**Comment by j0zzz** [comment]
Fixed in commit 09dc623
