### ISSUE TITLE
Ghost model is messed up with RoS

### ISSUE THREAD

**Issue by Flecked42** [j0zzz/JoeQuake#74]
![image](https://user-images.githubusercontent.com/90434262/200905897-f8aa24e8-5cc0-4d69-8621-126b09e22d7a.png)

**Comment by matthewearl** [comment]
We should switch to the eyes model, and otherwise respect the modelindex that is in the ghost demo.  There's probably a similar bug when the ghost gets gibbed.  I'll have a stab at fixing this.
