### ISSUE TITLE
Issue with 'cutscene' camera angles during demo playback

### ISSUE THREAD

**Issue by Flecked42** [j0zzz/JoeQuake#79]
The camera angle of 'cutscenes' during demo playback on map https://speeddemosarchive.com/quake/maps/parallax.zip is incorrect.

Happens in this demo https://speeddemosarchive.com/quake/demos/ER/para_410.dz at 1:35

Tested the demo in QS and the camera angles are correct.

**Comment by j0zzz** [comment]
Fixed in commit 0019cea
