### ISSUE TITLE
How do you use this source port?

### ISSUE THREAD

**Issue by DOOMMARINE117** [j0zzz/JoeQuake#8]
what files do i need?

**Comment by j0zzz** [comment]
Hello,
The complete package is available on the joequake project page for download:
http://joequake.runecentral.com/downloads.html

**Comment by DOOMMARINE117** [comment]
> 
> 
> Hello,
> The complete package is available on the joequake project page for download:
> http://joequake.runecentral.com/downloads.html

the version i should use is the 2020 version right?

 this one includes hipnotic_wad.zip an joequake_wad.zip?

**Comment by j0zzz** [comment]
You should use the latest version which is always at the top of the list, currently it is 'JoeQuake v0.16.2 build 6454 for Windows'.
It includes a newer version of hud images (joequake_wad). I think it does not contain the hipnotic mission pack related images, so I suggest to download the hipnotic_wad.zip and extract the contents to your hipnotic folder if you have the mssion pack.
