### ISSUE TITLE
crosshair 2 collides with hidden hipnotic feature

### ISSUE THREAD

**Issue by kugelrund** [j0zzz/JoeQuake#81]
Hipnotic mission pack has a hidden feature of playing footsteps when quake guy is walking around. Oddly enough this is enabled by setting `crosshair 2`. See https://www.gog.com/forum/quake_series/quake_scourge_of_armagon_by_hipnotic_real_footsteps_sounds . I suppose back then they were sure people would only ever have `crosshair 0` or `crosshair 1`.

Unfortunately, the alternate crosshair that JoeQuake provides with `crosshair 2` collides with this. So if you want to have that crosshair, then you are forced to play hipnotic with rather ugly footstep sounds that even end up in the demo.

A simple (fully backwards compatible) solution could be to add another crosshair (`crosshair 8`) that is just the same as `crosshair 2` which can then be used for playing hipnotic with that crosshair but without footstep sounds. Another option could be to add a new cvar entirely (`cl_customcrosshair` or something like that) and use that for selecting custom crosshairs (and maybe keep the old `crosshair >= 2` working for backwards compatibility, but don't encourage it anymore). Could also do a variant of any of those two options and not care about backwards comptatibility I suppose, it's not the worst breaking change, users will figure it out. Any thoughts?

**Comment by j0zzz** [comment]
I would definately go with the first solution, adding a new cvar for this is just overcomplicating for me, I'm sure if everybody would ask me about it after years, I wouldn't even remember what it's for :P
You can add the workaround if you want to, and thanks for finding/pointing out this bug.

**Comment by j0zzz** [comment]
Thanks for adding the fix!
