### ISSUE TITLE
Issue with mdls flickering black

### ISSUE THREAD

**Issue by Flecked42** [j0zzz/JoeQuake#83]
This is from a dev build, not the public 17.4.

https://user-images.githubusercontent.com/90434262/210886752-068db999-a881-42bb-958d-1a0dddba209d.mp4

I assume its from the swinging blades fix https://github.com/j0zzz/JoeQuake/issues/56

**Comment by Flecked42** [comment]
Maybe these commits could help

https://github.com/Novum/vkQuake/commit/496641026486b654c9ab69188327429093c48d39
https://github.com/andrei-drexler/ironwail/commit/ed0e44fbed3b0f25c602666a4d312150bb1105bd

**Comment by matthewearl** [comment]
I'm having trouble repro'ing this, even with a save state provided by @Flecked42 .  Having said that, it looks like [`ambientlight` and `shadelight` are not set if the trace from the origin succeeds](https://github.com/j0zzz/JoeQuake/blob/a0b0beb04d4211f86d910f8fe07dbafb4eb5590c/trunk/gl_rmain.c#L1389)

```c
	if (!R_LightPoint(ent->origin))
	{
		vec3_t lpos;
		VectorCopy(ent->origin, lpos);
		lpos[2] += ent->model->maxs[2] * 0.5f;
		ambientlight = shadelight = R_LightPoint(lpos);
	}
```

Maybe this could be the cause?

**Comment by matthewearl** [comment]
Never mind, I do see it with vertex lights off.  I've raised a PR which appears to fix the issue: https://github.com/j0zzz/JoeQuake/pull/84

**Comment by j0zzz** [comment]
Thanks a lot Matt!

**Comment by sezero** [comment]
Is the issue present in quakespasm? CC: @andrei-drexler

**Comment by Flecked42** [comment]
No I don't believe so. I've checked QS and didnt notice it.
