### ISSUE TITLE
Support external .ent files

### ISSUE THREAD

**Issue by Flecked42** [j0zzz/JoeQuake#85]
.ent files are basically entity list replacement for maps.

https://www.quaddicted.com/reviews/apsp1.html is a good map to test this on since there's a hotfix with a .ent file.

When the player reaches the bottom of the opening lift, there's another lift straight across that is out of place without the .ent file loaded.

QS commit for it https://github.com/sezero/quakespasm/commit/e25c9d2716ed1548d9efbb044e3c80dd404eb146

**Comment by j0zzz** [comment]
Fixed in commit c54b3e1
