### ISSUE TITLE
Issue with blending of lights

### ISSUE THREAD

**Issue by Flecked42** [j0zzz/JoeQuake#88]
Info is on QS https://github.com/sezero/quakespasm/issues/47

**Comment by Flecked42** [comment]
Test map with animated lights 
[lightbug.zip](https://github.com/j0zzz/JoeQuake/files/10540591/lightbug.zip)
Also bugged in QS

Test map with no animated lights 
[lightbug2.zip](https://github.com/j0zzz/JoeQuake/files/10540596/lightbug2.zip)
Also bugged in QS, but only with gl_overbright 0

The lights are supposed to be orange, not green.

**Comment by Flecked42** [comment]
![joequake004](https://user-images.githubusercontent.com/90434262/216788768-d55252ec-46ef-4632-bf8f-2602109ec4a4.png)

Took a closer look at the rocket explosion light and it looks like the same issue.

**Comment by j0zzz** [comment]
Fixed in commit a6192c0

**Comment by j0zzz** [comment]
Seems liek some light artifacting issue occurs on AMD cards.

**Comment by j0zzz** [comment]
Fixed light artifact issue in commit dc8d01f
