### ISSUE TITLE
MDLs are not properly lit by colored lights

### ISSUE THREAD

**Issue by Flecked42** [j0zzz/JoeQuake#90]
JQ
![joequake000](https://user-images.githubusercontent.com/90434262/235560375-4ee1ab42-2880-4435-ba93-5966f39e7dde.png)

QS
![spasm0000](https://user-images.githubusercontent.com/90434262/235560396-31592f7a-9b3e-4b37-a041-d56a184adf45.png)

map is e1m26_comfybythefire from coffee quake 2 https://speeddemosarchive.com/quake/maps/quoffee2.zip

**Comment by j0zzz** [comment]
This was never implemented, although I know QS has it for a long time. The models are properly lit when gl_vertexlights 1 is used. But I've been planning to add the fix from QS, for the default lighting mode too.

**Comment by j0zzz** [comment]
Added feature in commit c40f3c5
