### ISSUE TITLE
Issue with skybox

### ISSUE THREAD

**Issue by Flecked42** [j0zzz/JoeQuake#93]
Issue with skybox on the start map in Explore Jam 3 https://www.slipseer.com/index.php?resources/explore-jam-3.228/

JQ
![joequake000](https://github.com/j0zzz/JoeQuake/assets/90434262/ab47d19d-0965-40e5-8f1f-2b22038b5b0c)

QS
![spasm0000](https://github.com/j0zzz/JoeQuake/assets/90434262/155a3197-68c6-48c3-a889-ef5a56282f9b)

**Comment by Flecked42** [comment]
Sock the map author said:

"The start map uses a skybox called moody. All images are 512x512 in size, except the floor, its 4x4 pixels!?! this might be an issue for JQ."

**Comment by j0zzz** [comment]
Fixed in commit f3fc154
