### ISSUE TITLE
Map menu shows unplayable BSPs

### ISSUE THREAD

**Issue by Flecked42** [j0zzz/JoeQuake#94]
For example this is with AD loaded.
![joequake000](https://github.com/j0zzz/JoeQuake/assets/90434262/232de7da-0d63-44ec-9784-d30f3ff5067f)

This is what Ironwail did for its map menu, maybe will help.
https://github.com/andrei-drexler/ironwail/commit/65479e81d95b8079bcd76972954ccd40ca39b8c1

**Comment by j0zzz** [comment]
Fixed in commit f4f0081
