### ISSUE TITLE
Issue with loading maps with Mjolnir mod

### ISSUE THREAD

**Issue by Flecked42** [j0zzz/JoeQuake#96]
![joequake000](https://github.com/j0zzz/JoeQuake/assets/90434262/4ff93721-92eb-4413-b4c6-f4235df8cbfd)

Error happens when loading any map.

Maps load fine if you remove the progs.dat

The mod author said "I wonder if JoeQuake has some older pr_cmds size limitation preventing it from reading the full progs.dat or something.  It is rather large.  For a progs anyway"

Tested with QS and the maps load fine.

Link to the mod https://www.slipseer.com/index.php?resources/quake-mj%C3%B6lnir.243/

**Comment by j0zzz** [comment]
Same issue as #80

**Comment by j0zzz** [comment]
Fixed in commit 36fac91
