### ISSUE TITLE
Model scale support

### ISSUE THREAD

**Issue by Flecked42** [j0zzz/JoeQuake#98]
JQ
![joequake000](https://github.com/j0zzz/JoeQuake/assets/90434262/c8797d46-bba2-4bf1-a864-9658b6a4da69)

QS
![spasm0000](https://github.com/j0zzz/JoeQuake/assets/90434262/20970663-7141-46f4-ae96-4ced8ccd1e5c)

Images show map mj3m3 of Mjolnir. Its right at the player spawn.

QS commit for it 

https://github.com/sezero/quakespasm/commit/6ebf6f097a4cad0c87a16b3d7072de5104d94dda

I believe these commits are also relevant

https://github.com/sezero/quakespasm/commit/6bff9566a5a82d2f36e16530d99f743f491616f8
https://github.com/sezero/quakespasm/commit/239ec6623369a55e14b83ef100fd638abc3b875c
https://github.com/sezero/quakespasm/commit/dd8439b7671f69b1f183bb0d00099b371a06637c

**Comment by j0zzz** [comment]
Added in commits
078ff35
a223dd7
7598011
